apiVersion: apps/v1
kind: Deployment
metadata:
  name: manufacturing-monitor
  labels:
    app: manufacturing-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manufacturing-monitor
  template:
    metadata:
      labels:
        app: manufacturing-monitor
    spec:
      containers:
      - name: manufacturing-monitor
        image: your-registry/manufacturing-monitor:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: manufacturing-monitor-service
spec:
  selector:
    app: manufacturing-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  database-url: "postgresql://username:password@host:5432/database"